name: uprise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_core: ^4.7.0
  image_picker: ^1.0.0
  google_fonts: ^7.0.0
  file_picker: ^6.1.1
  excel: ^4.0.0
  csv: ^5.1.1
  mailer: ^6.0.1
  share_plus: ^7.2.1
  email_sender: ^2.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  printing: ^5.11.1
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ========== ADD YOUR ASSETS HERE ==========
  # To use images, create an 'assets' folder in the project root,
  # place your logo.png and bg_pattern.png inside it, then uncomment lines below.
  assets:
    - lib/assets/logo.png
    - lib/assets/bg_pattern.png
    # Add any other assets you need (e.g., default avatars, event images)