// Auto-issues a certificate the moment a student/guest submits event
// feedback — closing the gap left by org_certificates.dart's "Generate &
// Distribute" action, which only certifies whoever had *already* submitted
// feedback at the moment the org clicked it. Anyone who evaluates afterward
// would otherwise never get a certificate unless the org noticed and
// re-ran it manually.
//
// Mirrors exactly what a manual distribution writes (same certificate doc
// shape, same deterministic doc ID `${eventId}_${recipientKey}`) by copying
// the template/signatories off whichever certificate was already issued for
// this event — so it only fires once an org has distributed at least once,
// and never invents a template of its own.
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';

import 'notification_service.dart';

class CertificateAutoIssueService {
  static Future<void> tryIssueForFeedback({
    required String eventDocId,
    required String recipientKey, // studentId (uid) for students, email for guests
    required bool isGuest,
  }) async {
    try {
      final db = FirebaseFirestore.instance;
      final certsRef = db.collection('certificates');
      final docRef = certsRef.doc('${eventDocId}_$recipientKey');
      if ((await docRef.get()).exists) return; // already issued — nothing to do

      final attField = isGuest ? 'guestEmail' : 'studentId';
      final attSnap = await db
          .collection('events')
          .doc(eventDocId)
          .collection('attendances')
          .where(attField, isEqualTo: recipientKey)
          .limit(1)
          .get();
      if (attSnap.docs.isEmpty) return; // not marked as having attended
      final attData = attSnap.docs.first.data();
      final status = (attData['status'] ?? '').toString();
      if (status != 'present' && status != 'late') return;
      final recipientName = (attData['studentName'] ?? (isGuest ? 'Guest' : 'Student')).toString();

      // Don't just trust the caller to have written feedback right before
      // calling this — verify it directly, so "attended AND evaluated" holds
      // even if this is ever invoked from somewhere else in the future.
      final feedbackField = isGuest ? 'guestEmail' : 'userId';
      final feedbackSnap = await db
          .collection('event_feedback')
          .where('eventId', isEqualTo: eventDocId)
          .where(feedbackField, isEqualTo: recipientKey)
          .limit(1)
          .get();
      if (feedbackSnap.docs.isEmpty) return; // hasn't evaluated the event yet

      // An already-distributed certificate for this event supplies the
      // template/signatories to copy — if there isn't one yet, the org
      // hasn't generated certificates for this event at all, so there's
      // nothing to auto-issue against.
      final templateSnap = await certsRef
          .where('eventId', isEqualTo: eventDocId)
          .where('status', isEqualTo: 'distributed')
          .limit(1)
          .get();
      if (templateSnap.docs.isEmpty) return;
      final template = templateSnap.docs.first.data();

      await docRef.set({
        'orgId': template['orgId'],
        'eventId': eventDocId,
        'eventName': template['eventName'],
        'organization': template['organization'],
        'templateType': template['templateType'],
        'type': template['type'] ?? 'Participation',
        'issuedAt': FieldValue.serverTimestamp(),
        'status': 'distributed',
        'recipients': 1,
        'recipientName': recipientName,
        'isGuest': isGuest,
        'recipientId': recipientKey,
        'recipientUid': recipientKey,
        if (isGuest) 'recipientEmail': recipientKey,
        'signatories': template['signatories'] ?? [],
        'verificationCode': _generateVerificationCode(),
        'autoGenerated': true,
        if (template['templateFileUrl'] != null) 'templateFileUrl': template['templateFileUrl'],
        if (template['namePlacement'] != null) 'namePlacement': template['namePlacement'],
      });

      if (!isGuest) {
        await NotificationService.sendToUser(
          userId: recipientKey,
          title: 'Your certificate is ready 🎓',
          body: 'Your certificate for "${template['eventName']}" has been issued.',
          type: 'certificate',
          orgId: (template['orgId'] ?? '').toString(),
          data: {'eventId': eventDocId},
        );
      }
    } catch (_) {
      // Best-effort — a feedback submission must never fail because of this.
    }
  }

  static String _generateVerificationCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rng = Random.secure();
    return List.generate(12, (_) => chars[rng.nextInt(chars.length)]).join();
  }
}
