import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../../theme/app_theme.dart';
import '../../widgets/certificate_preview.dart';
import '../../widgets/student/app_colors.dart';
import 'student_feedback_screen.dart';
import '../../utils/feedback_helper.dart'; // 👈 IMPORT ITO

// ─────────────────────────────────────────────────────────────
//  STANDALONE SCREEN (uses CertificatesContent)
// ─────────────────────────────────────────────────────────────
class StudentCertificatesScreen extends StatelessWidget {
  const StudentCertificatesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Certificates',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      body: const CertificatesContent(),
    );
  }
}

// ─────────────────────────────────────────────────────────────
//  SHARED CONTENT WIDGET (used both standalone and as tab)
// ─────────────────────────────────────────────────────────────
class CertificatesContent extends StatefulWidget {
  const CertificatesContent({super.key});

  @override
  State<CertificatesContent> createState() => _CertificatesContentState();
}

class _CertificatesContentState extends State<CertificatesContent> {
  String selectedFilter = 'All';
  final List<String> filters = ['All', 'Academic', 'Workshops', 'Events'];

  List<Map<String, dynamic>> _allCertificates = [];
  bool _isLoading = true;
  String? _error;

  final String? _currentUid = FirebaseAuth.instance.currentUser?.uid;

  @override
  void initState() {
    super.initState();
    _fetchCertificates();
  }

  // ─────────────────────────────────────────────────────────────
  // FETCH (read‑only)
  // ─────────────────────────────────────────────────────────────
  Future<void> _fetchCertificates() async {
  try {
    final query = _currentUid != null
        ? FirebaseFirestore.instance
            .collection('certificates')
            .where('recipientUid', isEqualTo: _currentUid)
            // 👇 IDAGDAG ITO: HINDI KASAMA ANG DRAFT
            .where('status', isNotEqualTo: 'draft')
        : FirebaseFirestore.instance.collection('certificates');
    final snapshot = await query.get();

    var docs = snapshot.docs;

    docs.sort((a, b) {
      final aTs = a.data()['issuedAt'];
      final bTs = b.data()['issuedAt'];
      if (aTs == null && bTs == null) return 0;
      if (aTs == null) return 1;
      if (bTs == null) return -1;
      return (bTs as Timestamp).compareTo(aTs as Timestamp);
    });

    setState(() {
      _allCertificates = docs.map(_docToMap).toList();
      _isLoading = false;
    });
  } catch (e) {
    setState(() {
      _error = e.toString();
      _isLoading = false;
    });
  }
}

  Map<String, dynamic> _docToMap(QueryDocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return {
      'id'          : doc.id,
      'title'       : data['eventName'] ?? 'Untitled Certificate',
      'date'        : _formatDate(data['issuedAt']),
      'category'    : data['type'] ?? data['templateType'] ?? 'General',
      'organization': data['organization'] ?? '',
      'recipientName': data['recipientName'] ?? '',
      'signatories' : data['signatories'] is List ? data['signatories'] : const [],
      'status'      : data['status'] ?? 'draft',
      'recipients'  : data['recipients'] ?? 0,
      'templateType': data['templateType'] ?? '',
      'imageUrl'    : data['templateFileUrl'] ?? data['imageUrl'] ?? '',
      'isUploaded'  : data['isUploaded'] ?? false,
      'verificationCode' : data['verificationCode'] ?? '',
      'autoGenerated'    : data['autoGenerated'] ?? false,
      'eventId'     : data['eventId'] ?? '', // 👈 IDAGDAG ITO
    };
  }

  String _formatDate(dynamic timestamp) {
    if (timestamp == null) return 'Just now';
    if (timestamp is Timestamp) {
      final dt = timestamp.toDate();
      const months = [
        'January','February','March','April','May','June',
        'July','August','September','October','November','December'
      ];
      return '${months[dt.month - 1]} ${dt.day.toString().padLeft(2,'0')}, ${dt.year}';
    }
    return timestamp.toString();
  }

  // ── Helper: decode base64 image safely ─────────────────────────
  bool _isBase64Image(String url) =>
      url.startsWith('data:image') || (!url.startsWith('http') && url.isNotEmpty);

  Widget _buildImage(String imageUrl, {double height = 180}) {
    if (imageUrl.isEmpty) return const SizedBox.shrink();

    if (_isBase64Image(imageUrl)) {
      try {
        final base64Str = imageUrl.contains(',')
            ? imageUrl.split(',').last
            : imageUrl;
        final bytes = base64Decode(base64Str);
        return Image.memory(
          bytes,
          height: height,
          width: double.infinity,
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) => const SizedBox.shrink(),
        );
      } catch (_) {
        return const SizedBox.shrink();
      }
    }

    return Image.network(
      imageUrl,
      height: height,
      width: double.infinity,
      fit: BoxFit.cover,
      loadingBuilder: (context, child, loadingProgress) {
        if (loadingProgress == null) return child;
        return Container(
          height: height,
          color: AppColors.primaryDark.shade50,
          child: const Center(
            child: CircularProgressIndicator(color: AppColors.primaryDark),
          ),
        );
      },
      errorBuilder: (_, __, ___) => const SizedBox.shrink(),
    );
  }

  // ── Verification Dialog ──────────────────────────────────────────
  void _showVerifyDialog(Map<String, dynamic> cert) {
    final code = cert['verificationCode'] as String;
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (ctx) => Padding(
        padding: const EdgeInsets.fromLTRB(24, 20, 24, 32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Center(
              child: Container(
                width: 40, height: 4,
                margin: const EdgeInsets.only(bottom: 20),
                decoration: BoxDecoration(
                  color: Colors.grey.shade300,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const Icon(Icons.verified_rounded, color: Color(0xFF059669), size: 36),
            const SizedBox(height: 10),
            const Text('Certificate Verification',
                style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold, color: Colors.black87)),
            const SizedBox(height: 4),
            Text(cert['title'],
                style: TextStyle(fontSize: 13, color: Colors.grey.shade600),
                textAlign: TextAlign.center),
            const SizedBox(height: 20),
            Center(
              child: QrImageView(
                data: code,
                version: QrVersions.auto,
                size: 180,
                backgroundColor: Colors.white,
              ),
            ),
            const SizedBox(height: 16),
            Text('Verification Code',
                style: TextStyle(fontSize: 11, color: Colors.grey.shade500,
                    fontWeight: FontWeight.w600, letterSpacing: 0.5)),
            const SizedBox(height: 6),
            GestureDetector(
              onTap: () {
                Clipboard.setData(ClipboardData(text: code));
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                  content: Text('Code copied to clipboard'),
                  backgroundColor: Colors.green,
                  duration: Duration(seconds: 2),
                ));
              },
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                decoration: BoxDecoration(
                  color: const Color(0xFFFFF7ED),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0xFFFDE68A)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(code,
                        style: const TextStyle(
                            fontSize: 15, fontWeight: FontWeight.w700,
                            fontFamily: 'monospace', letterSpacing: 2,
                            color: Color(0xFFB45309))),
                    const SizedBox(width: 10),
                    const Icon(Icons.copy_rounded, size: 16, color: Color(0xFFB45309)),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),
            Text('Share this QR or code to verify authenticity.',
                style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
                textAlign: TextAlign.center),
          ],
        ),
      ),
    );
  }

  // ════════════════════════════════════════════════════════════════
  // 👇 BAGONG FUNCTION: Taga-check ng feedback bago mag-download
  // ════════════════════════════════════════════════════════════════
  Future<void> _downloadCertificate(Map<String, dynamic> cert) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      _showMessage('Please login first', isError: true);
      return;
    }

    // Show loading
    _showMessage('Checking feedback status...', isError: false);

    try {
      // Hanapin ang event ID
      String? eventId = cert['eventId'] as String?;
      
      // Kung walang eventId sa certificate, hanapin gamit ang event name
      if (eventId == null || eventId.isEmpty) {
        final eventName = cert['title'] as String;
        final eventQuery = await FirebaseFirestore.instance
            .collection('events')
            .where('title', isEqualTo: eventName)
            .limit(1)
            .get();
        
        if (eventQuery.docs.isNotEmpty) {
          eventId = eventQuery.docs.first.id;
        }
      }

      // Kung walang mahanap na event, sabihan ang user
      if (eventId == null) {
        _showMessage('⚠️ Cannot verify feedback. Please contact the organizer.', isError: true);
        return;
      }

      // ✅ ITO ANG IMPORTANTE: I-check kung may feedback na
      final hasFeedback = await FeedbackHelper.hasStudentGivenFeedback(
        studentId: user.uid,
        eventId: eventId,
      );

      if (!hasFeedback) {
        // ❌ WALANG FEEDBACK - Huwag payagan mag-download
        _showMessage(
          '⚠️ Please give feedback for this event first!',
          isError: true,
        );
        
        // Dalhin sa feedback screen
        _goToFeedback();
        return;
      }

      // ✅ MAY FEEDBACK NA - Payagan mag-download
      _showMessage('✅ ${cert['title']} downloaded!', isError: false);
      
      // 👇 DITO ILAGAY ANG ACTUAL DOWNLOAD CODE MO
      // Kung wala kang actual download code, ito muna:
      // (Yung original na ginagawa kapag nag-click ng download)
      
    } catch (e) {
      _showMessage('Error: $e', isError: true);
    }
  }

  // Helper: Magpakita ng message
  void _showMessage(String message, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red : Colors.green,
        duration: const Duration(seconds: 3),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  // Helper: Pumunta sa feedback screen
  void _goToFeedback() {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(
            backgroundColor: Colors.white,
            elevation: 0,
            foregroundColor: Colors.black87,
            title: const Text('Evaluate Events',
                style: TextStyle(fontWeight: FontWeight.w700, fontSize: 16)),
          ),
          body: const StudentFeedbackScreen(),
        ),
      ),
    );
  }

  // ── Certificate Card ──────────────────────────────────────────────
  Widget _buildCertificateCard(Map<String, dynamic> cert) {
    final isDraft    = cert['status'] == 'draft';
    final isUploaded = cert['isUploaded'] == true;
    final imageUrl   = cert['imageUrl'] as String;
    final canRenderLive = !isUploaded && (cert['organization'] as String).isNotEmpty;

    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withOpacity(0.07),
              blurRadius: 12,
              offset: const Offset(0, 4)),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            child: imageUrl.isNotEmpty
                ? _buildImage(imageUrl)
                : canRenderLive
                    ? _buildLivePreview(cert)
                    : _placeholderBanner(isDraft, isUploaded, cert),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(14, 12, 8, 12),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(cert['title'],
                          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black87)),
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                        decoration: BoxDecoration(
                          color: AppColors.primaryDark.shade50,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(cert['category'],
                            style: TextStyle(color: AppColors.primaryDark.shade700, fontSize: 11, fontWeight: FontWeight.w500)),
                      ),
                      const SizedBox(height: 4),
                      Text(cert['date'], style: TextStyle(color: Colors.grey.shade500, fontSize: 12)),
                      if (isUploaded) ...[
                        const SizedBox(height: 6),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: Colors.blue.shade50,
                            borderRadius: BorderRadius.circular(20),
                          ),
                          child: Text('Uploaded by you',
                              style: TextStyle(color: Colors.blue.shade600, fontSize: 11, fontWeight: FontWeight.w500)),
                        ),
                      ],
                    ],
                  ),
                ),
                // 👇 ITO YUNG DOWNLOAD BUTTON - PINALITAN NA
                GestureDetector(
                  onTap: () => _downloadCertificate(cert),
                  child: Container(
                    width: 40, height: 40,
                    decoration: BoxDecoration(color: AppColors.primaryDark, borderRadius: BorderRadius.circular(10)),
                    child: const Icon(Icons.download_rounded, color: Colors.white, size: 22),
                  ),
                ),
              ],
            ),
          ),
          // ── Verification QR ──
          if ((cert['verificationCode'] as String).isNotEmpty) ...[
            const Divider(height: 1, color: Color(0xFFF0F0F0)),
            GestureDetector(
              onTap: () => _showVerifyDialog(cert),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                child: Row(
                  children: [
                    QrImageView(
                      data: cert['verificationCode'] as String,
                      version: QrVersions.auto,
                      size: 44,
                      backgroundColor: Colors.white,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Verify Certificate',
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Colors.grey.shade800)),
                          const SizedBox(height: 2),
                          Text('Code: ${cert['verificationCode']}',
                              style: const TextStyle(fontSize: 11, fontFamily: 'monospace',
                                  letterSpacing: 1.1, color: Color(0xFFB45309), fontWeight: FontWeight.w600)),
                        ],
                      ),
                    ),
                    Icon(Icons.open_in_new_rounded, size: 16, color: Colors.grey.shade400),
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  // ── Live preview for non‑uploaded certificates ──────────────────
  Widget _buildLivePreview(Map<String, dynamic> cert) {
    final signatories = (cert['signatories'] as List)
        .whereType<Map>()
        .map((s) => CertSignatory(
              name: (s['name'] ?? '').toString(),
              title: (s['title'] ?? '').toString(),
              signatureImageBase64: s['signatureImage'] as String?,
            ))
        .toList();
    return Container(
      height: 180,
      width: double.infinity,
      color: const Color(0xFFF7F8FA),
      padding: const EdgeInsets.all(12),
      child: FittedBox(
        fit: BoxFit.contain,
        child: SizedBox(
          width: 600,
          height: 424,
          child: CertificatePreview(
            theme: CertTheme.forType(cert['templateType'] as String?,
                primaryDark: UpriseColors.primaryDark, primaryLight: UpriseColors.primaryLight, accentColor: UpriseColors.accent),
            orgName: cert['organization'] as String,
            eventTitle: cert['title'] as String,
            eventDate: cert['date'] as String,
            recipient: (cert['recipientName'] as String).isNotEmpty ? cert['recipientName'] as String : 'Recipient',
            signatories: signatories,
            verificationCode: (cert['verificationCode'] as String).isNotEmpty ? cert['verificationCode'] as String : null,
          ),
        ),
      ),
    );
  }

  Widget _placeholderBanner(bool isDraft, bool isUploaded, Map<String, dynamic> cert) {
    return Container(
      height: 180, width: double.infinity,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: isUploaded
              ? [Colors.blue.shade200, Colors.blue.shade500]
              : [AppColors.primaryDark.shade200, AppColors.primaryDark.shade500],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
      ),
      child: Stack(
        alignment: Alignment.center,
        children: [
          Icon(
            isUploaded ? Icons.upload_file_rounded : Icons.workspace_premium,
            size: 70, color: Colors.white24,
          ),
          if (isDraft)
            Positioned(
              top: 10, right: 10,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(color: Colors.black26, borderRadius: BorderRadius.circular(20)),
                child: const Text('DRAFT',
                    style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
              ),
            ),
          if ((cert['organization'] as String).isNotEmpty)
            Positioned(
              bottom: 10, left: 14,
              child: Text(cert['organization'],
                  style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.w500)),
            ),
        ],
      ),
    );
  }

  Widget _sectionLabel(String label) {
    return Text(label,
        style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: AppColors.primaryDark.shade700, letterSpacing: 0.4));
  }

  // ─── BUILD ──────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    final filtered = selectedFilter == 'All'
        ? _allCertificates
        : _allCertificates.where((c) => c['category'] == selectedFilter).toList();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Entry point to evaluate attended events
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
          child: GestureDetector(
            onTap: _goToFeedback, // 👈 PINALITAN NA
            child: Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: AppColors.primaryDark.withOpacity(0.08),
                borderRadius: BorderRadius.circular(14),
                border: Border.all(color: AppColors.primaryDark.withOpacity(0.2)),
              ),
              child: Row(children: [
                Icon(Icons.rate_review_rounded, color: AppColors.primaryDark, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text('Evaluate attended events',
                        style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: Colors.grey.shade800)),
                    Text('Required before your certificate can be issued',
                        style: TextStyle(fontSize: 11.5, color: Colors.grey.shade600)),
                  ]),
                ),
                Icon(Icons.chevron_right_rounded, color: AppColors.primaryDark),
              ]),
            ),
          ),
        ),
        const SizedBox(height: 4),
        // ── FILTER CHIPS ──
        SizedBox(
          height: 48,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 16),
            itemCount: filters.length,
            itemBuilder: (context, index) {
              final filter = filters[index];
              final isSelected = selectedFilter == filter;
              return GestureDetector(
                onTap: () => setState(() => selectedFilter = filter),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  margin: const EdgeInsets.only(right: 8, top: 6, bottom: 6),
                  padding: const EdgeInsets.symmetric(horizontal: 18),
                  decoration: BoxDecoration(
                    color: isSelected ? AppColors.primaryDark : Colors.white,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: isSelected ? AppColors.primaryDark : Colors.grey.shade300,
                    ),
                  ),
                  alignment: Alignment.center,
                  child: Text(filter,
                      style: TextStyle(
                          color: isSelected ? Colors.white : Colors.grey.shade600,
                          fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                          fontSize: 13)),
                ),
              );
            },
          ),
        ),
        const SizedBox(height: 8),

        // ── CONTENT ──
        Expanded(
          child: _isLoading
              ? const Center(child: CircularProgressIndicator(color: AppColors.primaryDark))
              : _error != null
                  ? Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Icon(Icons.error_outline, color: Colors.red, size: 48),
                          const SizedBox(height: 12),
                          Text('Failed to load certificates',
                              style: TextStyle(color: Colors.grey.shade700, fontWeight: FontWeight.w600)),
                          const SizedBox(height: 6),
                          Text(_error!, style: const TextStyle(color: Colors.red, fontSize: 12), textAlign: TextAlign.center),
                          const SizedBox(height: 12),
                          ElevatedButton(
                            onPressed: () {
                              setState(() { _isLoading = true; _error = null; });
                              _fetchCertificates();
                            },
                            style: ElevatedButton.styleFrom(backgroundColor: AppColors.primaryDark),
                            child: const Text('Retry', style: TextStyle(color: Colors.white)),
                          ),
                        ],
                      ),
                    )
                  : filtered.isEmpty
                      ? Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.workspace_premium_outlined, size: 64, color: Colors.grey.shade300),
                              const SizedBox(height: 12),
                              Text('No certificates found',
                                  style: TextStyle(color: Colors.grey.shade500, fontSize: 16)),
                            ],
                          ),
                        )
                      : RefreshIndicator(
                          color: AppColors.primaryDark,
                          onRefresh: _fetchCertificates,
                          child: ListView.builder(
                            padding: const EdgeInsets.only(left: 16, right: 16, top: 4, bottom: 16),
                            itemCount: filtered.length,
                            itemBuilder: (context, index) => _buildCertificateCard(filtered[index]),
                          ),
                        ),
        ),
      ],
    );
  }
}