import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../../theme/app_theme.dart';
import '../../widgets/certificate_preview.dart';

class StudentCertificatesScreen extends StatefulWidget {
  const StudentCertificatesScreen({super.key});

  @override
  State<StudentCertificatesScreen> createState() => _StudentCertificatesScreenState();
}

class _StudentCertificatesScreenState extends State<StudentCertificatesScreen> {
  String selectedFilter = 'All';
  final List<String> filters = ['All', 'Academic', 'Workshops', 'Events'];

  List<Map<String, dynamic>> _allCertificates = [];
  bool _isLoading = true;
  String? _error;

  final String? _currentUid = FirebaseAuth.instance.currentUser?.uid;
  final Set<String> _feedbackGiven = {};

  @override
  void initState() {
    super.initState();
    _fetchCertificates();
  }

  // ─────────────────────────────────────────────────────────────
  // FETCH (read‑only)
  // ─────────────────────────────────────────────────────────────
  Future<void> _fetchCertificates() async {
    try {
      final snapshot = await FirebaseFirestore.instance
          .collection('certificates')
          .get();

      var docs = snapshot.docs;

      if (_currentUid != null) {
        // Every certificate this app generates always sets recipientUid to
        // a specific person (see org_certificates.dart) — there's no
        // legitimate "broadcast to everyone" certificate type, so a missing
        // recipientUid should never match anyone, not fall through to
        // showing the certificate to every student.
        docs = docs.where((doc) => doc.data()['recipientUid'] == _currentUid).toList();
      }

      docs.sort((a, b) {
        final aTs = a.data()['issuedAt'];
        final bTs = b.data()['issuedAt'];
        if (aTs == null && bTs == null) return 0;
        if (aTs == null) return 1;
        if (bTs == null) return -1;
        return (bTs as Timestamp).compareTo(aTs as Timestamp);
      });

      setState(() {
        _allCertificates = docs.map(_docToMap).toList();
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _error = e.toString();
        _isLoading = false;
      });
    }
  }

  Map<String, dynamic> _docToMap(QueryDocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return {
      'id'          : doc.id,
      'title'       : data['eventName'] ?? 'Untitled Certificate',
      'date'        : _formatDate(data['issuedAt']),
      'category'    : data['type'] ?? data['templateType'] ?? 'General',
      'organization': data['organization'] ?? '',
      'recipientName': data['recipientName'] ?? '',
      // A custom design (from Customize or Import Template) is a flattened
      // image stored as templateFileUrl. `imageUrl` is only ever set by the
      // legacy/manual-upload path below — they're never both populated.
      'signatories' : data['signatories'] is List ? data['signatories'] : const [],
      'status'      : data['status'] ?? 'draft',
      'recipients'  : data['recipients'] ?? 0,
      'templateType': data['templateType'] ?? '',
      'imageUrl'    : data['templateFileUrl'] ?? data['imageUrl'] ?? '',
      'isUploaded'  : data['isUploaded'] ?? false,
      'verificationCode' : data['verificationCode'] ?? '',
      'autoGenerated'    : data['autoGenerated'] ?? false,
    };
  }

  String _formatDate(dynamic timestamp) {
    if (timestamp == null) return 'Just now';
    if (timestamp is Timestamp) {
      final dt = timestamp.toDate();
      const months = [
        'January','February','March','April','May','June',
        'July','August','September','October','November','December'
      ];
      return '${months[dt.month - 1]} ${dt.day.toString().padLeft(2,'0')}, ${dt.year}';
    }
    return timestamp.toString();
  }

  // ── Helper: decode base64 image safely ─────────────────────────
  bool _isBase64Image(String url) =>
      url.startsWith('data:image') || (!url.startsWith('http') && url.isNotEmpty);

  Widget _buildImage(String imageUrl, {double height = 180}) {
    if (imageUrl.isEmpty) return const SizedBox.shrink();

    if (_isBase64Image(imageUrl)) {
      try {
        final base64Str = imageUrl.contains(',')
            ? imageUrl.split(',').last
            : imageUrl;
        final bytes = base64Decode(base64Str);
        return Image.memory(
          bytes,
          height: height,
          width: double.infinity,
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) => const SizedBox.shrink(),
        );
      } catch (_) {
        return const SizedBox.shrink();
      }
    }

    return Image.network(
      imageUrl,
      height: height,
      width: double.infinity,
      fit: BoxFit.cover,
      loadingBuilder: (context, child, loadingProgress) {
        if (loadingProgress == null) return child;
        return Container(
          height: height,
          color: Colors.orange.shade50,
          child: const Center(
            child: CircularProgressIndicator(color: Colors.orange),
          ),
        );
      },
      errorBuilder: (_, __, ___) => const SizedBox.shrink(),
    );
  }

  // ── Feedback Dialog (unchanged) ──────────────────────────────────
  Future<void> _showFeedbackDialog(Map<String, dynamic> cert) async {
    int selectedRating = 0;
    final commentCtrl = TextEditingController();
    bool submitting = false;

    await showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setSheet) {
          Future<void> submit() async {
            if (selectedRating == 0) {
              ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                content: Text('Please select a star rating.'),
                backgroundColor: Colors.orange,
              ));
              return;
            }
            setSheet(() => submitting = true);
            try {
              await FirebaseFirestore.instance
                  .collection('event_feedback')
                  .add({
                'certId': cert['id'],
                'eventName': cert['title'],
                'organization': cert['organization'],
                'rating': selectedRating,
                'comment': commentCtrl.text.trim(),
                'userId': _currentUid,
                'submittedAt': FieldValue.serverTimestamp(),
              });
              if (mounted) setState(() => _feedbackGiven.add(cert['id']));
              if (ctx.mounted) Navigator.pop(ctx);
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                  content: Text('Feedback submitted. Thank you!'),
                  backgroundColor: Colors.green,
                ));
              }
            } catch (e) {
              setSheet(() => submitting = false);
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                  content: Text('Failed to submit: $e'),
                  backgroundColor: Colors.red,
                ));
              }
            }
          }

          return Padding(
            padding: EdgeInsets.only(
              bottom: MediaQuery.of(ctx).viewInsets.bottom,
              left: 20, right: 20, top: 20,
            ),
            child: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Center(
                    child: Container(
                      width: 40, height: 4,
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        color: Colors.grey.shade300,
                        borderRadius: BorderRadius.circular(2),
                      ),
                    ),
                  ),
                  const Text('Rate This Event',
                      style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.black87)),
                  const SizedBox(height: 4),
                  Text(cert['title'], style: TextStyle(fontSize: 13, color: Colors.grey.shade600)),
                  const SizedBox(height: 20),
                  Center(
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: List.generate(5, (i) {
                        final star = i + 1;
                        return GestureDetector(
                          onTap: () => setSheet(() => selectedRating = star),
                          child: Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 6),
                            child: Icon(
                              star <= selectedRating ? Icons.star_rounded : Icons.star_outline_rounded,
                              size: 40,
                              color: star <= selectedRating ? Colors.orange : Colors.grey.shade300,
                            ),
                          ),
                        );
                      }),
                    ),
                  ),
                  const SizedBox(height: 20),
                  TextField(
                    controller: commentCtrl,
                    maxLines: 3,
                    decoration: InputDecoration(
                      hintText: 'Share your experience (optional)...',
                      hintStyle: TextStyle(color: Colors.grey.shade400),
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Colors.orange, width: 2),
                      ),
                      contentPadding: const EdgeInsets.all(14),
                    ),
                  ),
                  const SizedBox(height: 20),
                  SizedBox(
                    width: double.infinity, height: 52,
                    child: ElevatedButton(
                      onPressed: submitting ? null : submit,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.orange,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                      ),
                      child: submitting
                          ? const SizedBox(width: 22, height: 22,
                              child: CircularProgressIndicator(strokeWidth: 2.5, color: Colors.white))
                          : const Text('Submit Feedback',
                              style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
                    ),
                  ),
                  const SizedBox(height: 24),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  // ── Verification Dialog ──────────────────────────────────────────
  void _showVerifyDialog(Map<String, dynamic> cert) {
    final code = cert['verificationCode'] as String;
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (ctx) => Padding(
        padding: const EdgeInsets.fromLTRB(24, 20, 24, 32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Center(
              child: Container(
                width: 40, height: 4,
                margin: const EdgeInsets.only(bottom: 20),
                decoration: BoxDecoration(
                  color: Colors.grey.shade300,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const Icon(Icons.verified_rounded, color: Color(0xFF059669), size: 36),
            const SizedBox(height: 10),
            const Text('Certificate Verification',
                style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold, color: Colors.black87)),
            const SizedBox(height: 4),
            Text(cert['title'],
                style: TextStyle(fontSize: 13, color: Colors.grey.shade600),
                textAlign: TextAlign.center),
            const SizedBox(height: 20),
            Center(
              child: QrImageView(
                data: code,
                version: QrVersions.auto,
                size: 180,
                backgroundColor: Colors.white,
              ),
            ),
            const SizedBox(height: 16),
            Text('Verification Code',
                style: TextStyle(fontSize: 11, color: Colors.grey.shade500,
                    fontWeight: FontWeight.w600, letterSpacing: 0.5)),
            const SizedBox(height: 6),
            GestureDetector(
              onTap: () {
                Clipboard.setData(ClipboardData(text: code));
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                  content: Text('Code copied to clipboard'),
                  backgroundColor: Colors.green,
                  duration: Duration(seconds: 2),
                ));
              },
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                decoration: BoxDecoration(
                  color: const Color(0xFFFFF7ED),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0xFFFDE68A)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(code,
                        style: const TextStyle(
                            fontSize: 15, fontWeight: FontWeight.w700,
                            fontFamily: 'monospace', letterSpacing: 2,
                            color: Color(0xFFB45309))),
                    const SizedBox(width: 10),
                    const Icon(Icons.copy_rounded, size: 16, color: Color(0xFFB45309)),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),
            Text('Share this QR or code to verify authenticity.',
                style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
                textAlign: TextAlign.center),
          ],
        ),
      ),
    );
  }

  // ── Certificate Card ──────────────────────────────────────────────
  Widget _buildCertificateCard(Map<String, dynamic> cert) {
    final isDraft    = cert['status'] == 'draft';
    final isUploaded = cert['isUploaded'] == true;
    final imageUrl   = cert['imageUrl'] as String;
    final canRenderLive = !isUploaded && (cert['organization'] as String).isNotEmpty;

    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withOpacity(0.07),
              blurRadius: 12,
              offset: const Offset(0, 4)),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            child: imageUrl.isNotEmpty
                ? _buildImage(imageUrl)
                : canRenderLive
                    ? _buildLivePreview(cert)
                    : _placeholderBanner(isDraft, isUploaded, cert),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(14, 12, 8, 12),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(cert['title'],
                          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black87)),
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                        decoration: BoxDecoration(
                          color: Colors.orange.shade50,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(cert['category'],
                            style: TextStyle(color: Colors.orange.shade700, fontSize: 11, fontWeight: FontWeight.w500)),
                      ),
                      const SizedBox(height: 4),
                      Text(cert['date'], style: TextStyle(color: Colors.grey.shade500, fontSize: 12)),
                      if (isUploaded) ...[
                        const SizedBox(height: 6),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: Colors.blue.shade50,
                            borderRadius: BorderRadius.circular(20),
                          ),
                          child: Text('Uploaded by you',
                              style: TextStyle(color: Colors.blue.shade600, fontSize: 11, fontWeight: FontWeight.w500)),
                        ),
                      ],
                    ],
                  ),
                ),
                // Download button (stub)
                GestureDetector(
                  onTap: () {
                    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                      content: Text('${cert['title']} downloaded'),
                      backgroundColor: Colors.orange,
                    ));
                  },
                  child: Container(
                    width: 40, height: 40,
                    decoration: BoxDecoration(color: Colors.orange, borderRadius: BorderRadius.circular(10)),
                    child: const Icon(Icons.download_rounded, color: Colors.white, size: 22),
                  ),
                ),
              ],
            ),
          ),
          // ── Feedback Button ──
          if (cert['status'] != 'draft') ...[
            const Divider(height: 1, color: Color(0xFFF0F0F0)),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
              child: _feedbackGiven.contains(cert['id'])
                  ? Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(Icons.check_circle, size: 15, color: Colors.green.shade600),
                        const SizedBox(width: 6),
                        Text('Feedback submitted',
                            style: TextStyle(fontSize: 12, color: Colors.green.shade600, fontWeight: FontWeight.w500)),
                      ],
                    )
                  : GestureDetector(
                      onTap: () => _showFeedbackDialog(cert),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(Icons.star_outline, size: 16, color: Colors.orange.shade600),
                          const SizedBox(width: 6),
                          Text('Rate this event',
                              style: TextStyle(fontSize: 12, color: Colors.orange.shade600, fontWeight: FontWeight.w600)),
                        ],
                      ),
                    ),
            ),
          ],
          // ── Verification QR ──
          if ((cert['verificationCode'] as String).isNotEmpty) ...[
            const Divider(height: 1, color: Color(0xFFF0F0F0)),
            GestureDetector(
              onTap: () => _showVerifyDialog(cert),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                child: Row(
                  children: [
                    QrImageView(
                      data: cert['verificationCode'] as String,
                      version: QrVersions.auto,
                      size: 44,
                      backgroundColor: Colors.white,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Verify Certificate',
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Colors.grey.shade800)),
                          const SizedBox(height: 2),
                          Text('Code: ${cert['verificationCode']}',
                              style: const TextStyle(fontSize: 11, fontFamily: 'monospace',
                                  letterSpacing: 1.1, color: Color(0xFFB45309), fontWeight: FontWeight.w600)),
                        ],
                      ),
                    ),
                    Icon(Icons.open_in_new_rounded, size: 16, color: Colors.grey.shade400),
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  // Certificates that weren't built from a custom-designed/imported
  // template have no flattened image at all — there's nothing per-recipient
  // to flatten consistently. Rendered live here instead, straight from the
  // same fields the org filled in, using the exact widget the org sees in
  // their own Generate/Customize/View flows — so it always carries this
  // student's actual name, not a shared placeholder graphic.
  Widget _buildLivePreview(Map<String, dynamic> cert) {
    final signatories = (cert['signatories'] as List)
        .whereType<Map>()
        .map((s) => CertSignatory(
              name: (s['name'] ?? '').toString(),
              title: (s['title'] ?? '').toString(),
              signatureImageBase64: s['signatureImage'] as String?,
            ))
        .toList();
    return Container(
      height: 180,
      width: double.infinity,
      color: const Color(0xFFF7F8FA),
      padding: const EdgeInsets.all(12),
      child: FittedBox(
        fit: BoxFit.contain,
        child: SizedBox(
          width: 600,
          height: 424,
          child: CertificatePreview(
            theme: CertTheme.forType(cert['templateType'] as String?,
                primaryDark: UpriseColors.primaryDark, primaryLight: UpriseColors.primaryLight, accentColor: UpriseColors.accent),
            orgName: cert['organization'] as String,
            eventTitle: cert['title'] as String,
            eventDate: cert['date'] as String,
            recipient: (cert['recipientName'] as String).isNotEmpty ? cert['recipientName'] as String : 'Recipient',
            signatories: signatories,
            verificationCode: (cert['verificationCode'] as String).isNotEmpty ? cert['verificationCode'] as String : null,
          ),
        ),
      ),
    );
  }

  Widget _placeholderBanner(bool isDraft, bool isUploaded, Map<String, dynamic> cert) {
    return Container(
      height: 180, width: double.infinity,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: isUploaded
              ? [Colors.blue.shade200, Colors.blue.shade500]
              : [Colors.orange.shade200, Colors.orange.shade500],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
      ),
      child: Stack(
        alignment: Alignment.center,
        children: [
          Icon(
            isUploaded ? Icons.upload_file_rounded : Icons.workspace_premium,
            size: 70, color: Colors.white24,
          ),
          if (isDraft)
            Positioned(
              top: 10, right: 10,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(color: Colors.black26, borderRadius: BorderRadius.circular(20)),
                child: const Text('DRAFT',
                    style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 1.2)),
              ),
            ),
          if ((cert['organization'] as String).isNotEmpty)
            Positioned(
              bottom: 10, left: 14,
              child: Text(cert['organization'],
                  style: const TextStyle(color: Colors.white70, fontSize: 12, fontWeight: FontWeight.w500)),
            ),
        ],
      ),
    );
  }

  Widget _sectionLabel(String label) {
    return Text(label,
        style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: Colors.orange.shade700, letterSpacing: 0.4));
  }

  // ─── BUILD ──────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    final filtered = selectedFilter == 'All'
        ? _allCertificates
        : _allCertificates.where((c) => c['category'] == selectedFilter).toList();

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text('Certificates',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.black)),
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      // No floatingActionButton
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── FILTER CHIPS ──
          SizedBox(
            height: 48,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: 16),
              itemCount: filters.length,
              itemBuilder: (context, index) {
                final filter = filters[index];
                final isSelected = selectedFilter == filter;
                return GestureDetector(
                  onTap: () => setState(() => selectedFilter = filter),
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 200),
                    margin: const EdgeInsets.only(right: 8, top: 6, bottom: 6),
                    padding: const EdgeInsets.symmetric(horizontal: 18),
                    decoration: BoxDecoration(
                      color: isSelected ? Colors.orange : Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(
                        color: isSelected ? Colors.orange : Colors.grey.shade300,
                      ),
                    ),
                    alignment: Alignment.center,
                    child: Text(filter,
                        style: TextStyle(
                            color: isSelected ? Colors.white : Colors.grey.shade600,
                            fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                            fontSize: 13)),
                  ),
                );
              },
            ),
          ),
          const SizedBox(height: 8),

          // ── CONTENT ──
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator(color: Colors.orange))
                : _error != null
                    ? Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Icon(Icons.error_outline, color: Colors.red, size: 48),
                            const SizedBox(height: 12),
                            Text('Failed to load certificates',
                                style: TextStyle(color: Colors.grey.shade700, fontWeight: FontWeight.w600)),
                            const SizedBox(height: 6),
                            Text(_error!, style: const TextStyle(color: Colors.red, fontSize: 12), textAlign: TextAlign.center),
                            const SizedBox(height: 12),
                            ElevatedButton(
                              onPressed: () {
                                setState(() { _isLoading = true; _error = null; });
                                _fetchCertificates();
                              },
                              style: ElevatedButton.styleFrom(backgroundColor: Colors.orange),
                              child: const Text('Retry', style: TextStyle(color: Colors.white)),
                            ),
                          ],
                        ),
                      )
                    : filtered.isEmpty
                        ? Center(
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(Icons.workspace_premium_outlined, size: 64, color: Colors.grey.shade300),
                                const SizedBox(height: 12),
                                Text('No certificates found',
                                    style: TextStyle(color: Colors.grey.shade500, fontSize: 16)),
                              ],
                            ),
                          )
                        : RefreshIndicator(
                            color: Colors.orange,
                            onRefresh: _fetchCertificates,
                            child: ListView.builder(
                              padding: const EdgeInsets.only(left: 16, right: 16, top: 4, bottom: 90),
                              itemCount: filtered.length,
                              itemBuilder: (context, index) => _buildCertificateCard(filtered[index]),
                            ),
                          ),
          ),
        ],
      ),
    );
  }
}