import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class OrgExportPdf {
  /// Shared branded header: UPRISE + CICT + BSU logos, plus the org's own
  /// logo when one is supplied — every export across the app should pass
  /// its org's logo bytes here so the org is represented alongside the
  /// university branding, not just generically.
  static pw.Widget _brandHeader({
    required pw.MemoryImage? upriseLogo,
    required pw.MemoryImage? cictLogo,
    required pw.MemoryImage? bsuLogo,
    pw.MemoryImage? orgLogo,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 28),
      child: pw.Center(
        child: pw.Row(
          mainAxisSize: pw.MainAxisSize.min,
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            if (upriseLogo != null) pw.Image(upriseLogo, height: 36),
            if (upriseLogo != null && cictLogo != null) pw.SizedBox(width: 18),
            if (cictLogo != null) pw.Image(cictLogo, height: 40),
            if ((upriseLogo != null || cictLogo != null) && bsuLogo != null) pw.SizedBox(width: 18),
            if (bsuLogo != null) pw.Image(bsuLogo, height: 50),
            if (orgLogo != null) ...[
              pw.SizedBox(width: 18),
              pw.Container(height: 36, width: 1, color: PdfColors.grey400),
              pw.SizedBox(width: 18),
              pw.Image(orgLogo, height: 40),
            ],
          ],
        ),
      ),
    );
  }

  static pw.Widget _brandFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 18),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Divider(color: PdfColors.grey400, thickness: 0.5),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Uprise',
                style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
              pw.Text(
                'Page ${context.pageNumber}',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Decodes a logo that may be a base64 data URI (most org logos in this
  /// app are stored that way) or leaves it null if absent/unparseable.
  static pw.MemoryImage? _decodeOrgLogo(String? orgLogoUrlOrBase64) {
    if (orgLogoUrlOrBase64 == null || orgLogoUrlOrBase64.isEmpty) return null;
    try {
      final raw = orgLogoUrlOrBase64.contains(',')
          ? orgLogoUrlOrBase64.split(',').last
          : orgLogoUrlOrBase64;
      return pw.MemoryImage(base64Decode(raw));
    } catch (_) {
      return null;
    }
  }

  static Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String subtitle = 'Bulacan State University - College of Information and Communications Technology (CICT)',
    String? orgLogoUrl,
  }) async {
    final pdf = pw.Document();
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final orgLogo = _decodeOrgLogo(orgLogoUrl);
    final now = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _brandHeader(
          upriseLogo: upriseLogo, cictLogo: cictLogo, bsuLogo: bsuLogo, orgLogo: orgLogo,
        ),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 18, horizontal: 20),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(10),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  subtitle,
                  style: pw.TextStyle(fontSize: 12, fontStyle: pw.FontStyle.italic, color: PdfColors.grey700),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  'Uprise Student Directory System',
                  style: pw.TextStyle(fontSize: 11, color: PdfColors.grey800),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Generated: $now',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 18),
          pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.orange300, width: 1),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Table(
              defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
              columnWidths: {
                for (var i = 0; i < headers.length; i++) i: const pw.FlexColumnWidth(1),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.orange400),
                  children: headers.map((header) {
                    return pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 12, horizontal: 8),
                      child: pw.Text(
                        header,
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
                        textAlign: pw.TextAlign.center,
                      ),
                    );
                  }).toList(),
                ),
                ...rows.asMap().entries.map((entry) {
                  final row = entry.value;
                  final index = entry.key;
                  return pw.TableRow(
                    decoration: index.isEven ? const pw.BoxDecoration(color: PdfColors.orange100) : null,
                    children: List.generate(headers.length, (cellIndex) {
                      final value = cellIndex < row.length ? row[cellIndex] : '';
                      return pw.Padding(
                        padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 8),
                        child: pw.Text(value, style: pw.TextStyle(fontSize: 10, color: PdfColors.grey900)),
                      );
                    }),
                  );
                }),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  /// A proper financial statement layout — Cash Inflow and Cash Outflow
  /// sections, each with its own subtotal, plus a Net Cash Flow total —
  /// instead of a flat transaction table. `inflowRows`/`outflowRows` are
  /// `[date, event, category, description, amount]`; amounts are pre-
  /// formatted strings (e.g. "₱1,250.00") so currency formatting stays the
  /// caller's responsibility.
  static Future<Uint8List> generateFinancialReportPdf({
    required String orgName,
    required String periodLabel,
    required List<List<String>> inflowRows,
    required List<List<String>> outflowRows,
    required double totalInflow,
    required double totalOutflow,
    String? orgLogoUrl,
  }) async {
    final pdf = pw.Document();
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final orgLogo = _decodeOrgLogo(orgLogoUrl);
    final now = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());
    final currency = NumberFormat.currency(locale: 'en_PH', symbol: '₱');
    final netFlow = totalInflow - totalOutflow;

    const colHeaders = ['Date', 'Event', 'Category', 'Description', 'Amount'];

    pw.Widget sectionTable(String label, PdfColor color, List<List<String>> rows, double subtotal) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
            color: color,
            width: double.infinity,
            child: pw.Text(label,
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.white)),
          ),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.6),
            defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
            columnWidths: const {
              0: pw.FlexColumnWidth(1.3),
              1: pw.FlexColumnWidth(1.8),
              2: pw.FlexColumnWidth(1.3),
              3: pw.FlexColumnWidth(2.2),
              4: pw.FlexColumnWidth(1.2),
            },
            children: [
              pw.TableRow(
                decoration: pw.BoxDecoration(color: PdfColors.grey200),
                children: colHeaders
                    .map((h) => pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 6),
                          child: pw.Text(h, style: pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold)),
                        ))
                    .toList(),
              ),
              if (rows.isEmpty)
                pw.TableRow(children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 6),
                    child: pw.Text('No transactions for this period.',
                        style: pw.TextStyle(fontSize: 9.5, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic)),
                  ),
                  ...List.generate(4, (_) => pw.Container()),
                ]),
              ...rows.map((row) => pw.TableRow(
                    children: List.generate(5, (i) => pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(vertical: 7, horizontal: 6),
                          child: pw.Text(i < row.length ? row[i] : '', style: pw.TextStyle(fontSize: 9.5)),
                        )),
                  )),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
            decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300, width: 0.6)),
            width: double.infinity,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.end,
              children: [
                pw.Text('Subtotal: ', style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold)),
                pw.Text(currency.format(subtotal),
                    style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold, color: color)),
              ],
            ),
          ),
        ],
      );
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _brandHeader(
          upriseLogo: upriseLogo, cictLogo: cictLogo, bsuLogo: bsuLogo, orgLogo: orgLogo,
        ),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 18, horizontal: 20),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(10),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text('Financial Report',
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                    textAlign: pw.TextAlign.center),
                pw.SizedBox(height: 8),
                pw.Text(orgName,
                    style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.grey800),
                    textAlign: pw.TextAlign.center),
                pw.SizedBox(height: 4),
                pw.Text('Period: $periodLabel',
                    style: pw.TextStyle(fontSize: 11, fontStyle: pw.FontStyle.italic, color: PdfColors.grey700),
                    textAlign: pw.TextAlign.center),
                pw.SizedBox(height: 4),
                pw.Text('Generated: $now', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          sectionTable('CASH INFLOW (Income)', PdfColors.green700, inflowRows, totalInflow),
          pw.SizedBox(height: 18),
          sectionTable('CASH OUTFLOW (Expenses)', PdfColors.red700, outflowRows, totalOutflow),
          pw.SizedBox(height: 20),
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: netFlow >= 0 ? PdfColors.green50 : PdfColors.red50,
              border: pw.Border.all(color: netFlow >= 0 ? PdfColors.green700 : PdfColors.red700, width: 1),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Total Cash Inflow', style: pw.TextStyle(fontSize: 11)),
                  pw.Text(currency.format(totalInflow), style: pw.TextStyle(fontSize: 11)),
                ],
              ),
              pw.SizedBox(height: 4),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Total Cash Outflow', style: pw.TextStyle(fontSize: 11)),
                  pw.Text('(${currency.format(totalOutflow)})', style: pw.TextStyle(fontSize: 11)),
                ],
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 8),
                child: pw.Divider(color: PdfColors.grey400, thickness: 0.8),
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('NET CASH FLOW',
                      style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                  pw.Text(currency.format(netFlow),
                      style: pw.TextStyle(
                          fontSize: 13,
                          fontWeight: pw.FontWeight.bold,
                          color: netFlow >= 0 ? PdfColors.green700 : PdfColors.red700)),
                ],
              ),
            ]),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static Future<pw.MemoryImage?> _loadImage(String path) async {
    try {
      final byteData = await rootBundle.load(path);
      return pw.MemoryImage(byteData.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }
}
