import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class OrgExportPdf {
  static const PdfColor _accent = PdfColor.fromInt(0xFFBE4700);

  // The default PDF base font (Helvetica) has no ₱ glyph, so it silently
  // drops the peso sign — fall back to Noto Sans (which does have it) only
  // for characters Helvetica can't draw, so normal text is unaffected.
  static Future<pw.ThemeData>? _themeFuture;
  static Future<pw.ThemeData> _loadTheme() {
    return _themeFuture ??= PdfGoogleFonts.notoSansRegular().then(
      (font) => pw.ThemeData.withFont(fontFallback: [font]),
    );
  }

  /// Letterhead: UPRISE + CICT + BSU logos, plus the org's own logo when
  /// supplied, sitting above a brand accent rule and a small-caps
  /// institution line — every export across the app should pass its org's
  /// logo bytes here so the org is represented alongside the university
  /// branding, not just generically.
  static pw.Widget _brandHeader({
    required pw.MemoryImage? upriseLogo,
    required pw.MemoryImage? cictLogo,
    required pw.MemoryImage? bsuLogo,
    pw.MemoryImage? orgLogo,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 22),
      child: pw.Column(
        children: [
          pw.Row(
            mainAxisSize: pw.MainAxisSize.min,
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              if (upriseLogo != null) pw.Image(upriseLogo, height: 34),
              if (upriseLogo != null && bsuLogo != null) pw.SizedBox(width: 16),
              if (bsuLogo != null) pw.Image(bsuLogo, height: 46),
              if ((upriseLogo != null || bsuLogo != null) && cictLogo != null) pw.SizedBox(width: 16),
              if (cictLogo != null) pw.Image(cictLogo, height: 38),
              if (orgLogo != null) ...[
                pw.SizedBox(width: 16),
                pw.Container(height: 32, width: 1, color: PdfColors.grey400),
                pw.SizedBox(width: 16),
                pw.Image(orgLogo, height: 38),
              ],
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Container(height: 2, width: double.infinity, color: _accent),
          pw.SizedBox(height: 6),
          pw.Text(
            'BULACAN STATE UNIVERSITY  |  COLLEGE OF INFORMATION AND COMMUNICATIONS TECHNOLOGY',
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 7, color: PdfColors.grey600, letterSpacing: 0.6),
          ),
        ],
      ),
    );
  }

  static pw.Widget _brandFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 14),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Container(height: 0.75, width: double.infinity, color: PdfColors.grey300),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Uprise - CICT Organization Management System',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 8.5, color: PdfColors.grey600, fontWeight: pw.FontWeight.bold),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Letterhead-style title block: small-caps eyebrow label, bold title,
  /// optional subtitle, a short accent underline, then the generated-at
  /// timestamp — replaces the old boxed grey card with a cleaner document
  /// look.
  static pw.Widget _titleBlock({
    required String eyebrow,
    required String title,
    String? subtitle,
    required String generatedAt,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          eyebrow,
          style: pw.TextStyle(
              fontSize: 9, color: _accent, fontWeight: pw.FontWeight.bold, letterSpacing: 2.2),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          title,
          textAlign: pw.TextAlign.center,
          style: pw.TextStyle(fontSize: 23, fontWeight: pw.FontWeight.bold, color: PdfColors.grey900),
        ),
        if (subtitle != null && subtitle.isNotEmpty) ...[
          pw.SizedBox(height: 5),
          pw.Text(
            subtitle,
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
        pw.SizedBox(height: 10),
        pw.Container(width: 64, height: 2.2, color: _accent),
        pw.SizedBox(height: 10),
        pw.Text('Generated $generatedAt', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),
      ],
    );
  }

  /// Decodes a logo that may be a base64 data URI (most org logos in this
  /// app are stored that way) or leaves it null if absent/unparseable.
  static pw.MemoryImage? _decodeOrgLogo(String? orgLogoUrlOrBase64) {
    if (orgLogoUrlOrBase64 == null || orgLogoUrlOrBase64.isEmpty) return null;
    try {
      final raw = orgLogoUrlOrBase64.contains(',')
          ? orgLogoUrlOrBase64.split(',').last
          : orgLogoUrlOrBase64;
      return pw.MemoryImage(base64Decode(raw));
    } catch (_) {
      return null;
    }
  }

  static Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String subtitle = 'Official organization records export',
    String? orgLogoUrl,
  }) async {
    final pdf = pw.Document(theme: await _loadTheme());
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final orgLogo = _decodeOrgLogo(orgLogoUrl);
    final now = DateFormat('MMMM d, yyyy \'at\' h:mm a').format(DateTime.now());

    final pageFormat = headers.length > 5 ? PdfPageFormat.a4.landscape : PdfPageFormat.a4;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: pageFormat,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 28),
        header: (context) => _brandHeader(
          upriseLogo: upriseLogo, cictLogo: cictLogo, bsuLogo: bsuLogo, orgLogo: orgLogo,
        ),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          pw.Center(
            child: _titleBlock(
              eyebrow: 'EXPORTED RECORD',
              title: title,
              subtitle: subtitle,
              generatedAt: now,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
            margin: const pw.EdgeInsets.only(bottom: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Text(
              '${rows.length} record${rows.length == 1 ? '' : 's'}',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Table(
            border: const pw.TableBorder(
              horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
            ),
            defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
            columnWidths: {
              for (var i = 0; i < headers.length; i++)
                i: pw.FlexColumnWidth(headers[i].length.toDouble().clamp(8, 22)),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                  color: _accent,
                  borderRadius: pw.BorderRadius.vertical(top: pw.Radius.circular(4)),
                ),
                children: headers.map((header) {
                  return pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 8),
                    child: pw.Text(
                      header.toUpperCase(),
                      style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white, letterSpacing: 0.4),
                      textAlign: pw.TextAlign.center,
                    ),
                  );
                }).toList(),
              ),
              ...rows.asMap().entries.map((entry) {
                final row = entry.value;
                final index = entry.key;
                return pw.TableRow(
                  decoration: index.isEven ? const pw.BoxDecoration(color: PdfColors.orange50) : null,
                  children: List.generate(headers.length, (cellIndex) {
                    final value = cellIndex < row.length ? row[cellIndex] : '';
                    return pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 9, horizontal: 8),
                      child: pw.Text(value, style: pw.TextStyle(fontSize: 9.5, color: PdfColors.grey900)),
                    );
                  }),
                );
              }),
            ],
          ),
          if (rows.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 20),
              child: pw.Center(
                child: pw.Text('No records to display.',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic)),
              ),
            ),
        ],
      ),
    );

    return pdf.save();
  }

  /// A proper financial statement layout — Cash Inflow and Cash Outflow
  /// sections, each with its own subtotal, plus a Net Cash Flow total —
  /// instead of a flat transaction table. `inflowRows`/`outflowRows` are
  /// `[date, event, category, description, amount]`; amounts are pre-
  /// formatted strings (e.g. "₱1,250.00") so currency formatting stays the
  /// caller's responsibility.
  static Future<Uint8List> generateFinancialReportPdf({
    required String orgName,
    required String periodLabel,
    required List<List<String>> inflowRows,
    required List<List<String>> outflowRows,
    required double totalInflow,
    required double totalOutflow,
    String? orgLogoUrl,
  }) async {
    final pdf = pw.Document(theme: await _loadTheme());
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final orgLogo = _decodeOrgLogo(orgLogoUrl);
    final now = DateFormat('MMMM d, yyyy \'at\' h:mm a').format(DateTime.now());
    // The default PDF font has no glyph for the ₱ symbol — it renders as a
    // missing-character box. 'PHP ' renders correctly in every font.
    final currency = NumberFormat.currency(locale: 'en_PH', symbol: 'PHP ');
    final netFlow = totalInflow - totalOutflow;

    const colHeaders = ['Date', 'Event', 'Category', 'Description', 'Amount'];

    pw.Widget sectionTable(String label, PdfColor color, List<List<String>> rows, double subtotal) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 7, horizontal: 10),
            decoration: pw.BoxDecoration(
              color: color,
              borderRadius: const pw.BorderRadius.vertical(top: pw.Radius.circular(5)),
            ),
            width: double.infinity,
            child: pw.Text(label,
                style: pw.TextStyle(
                    fontSize: 11.5, fontWeight: pw.FontWeight.bold, color: PdfColors.white, letterSpacing: 0.6)),
          ),
          pw.Table(
            border: pw.TableBorder(
              left: pw.BorderSide(color: PdfColors.grey300, width: 0.6),
              right: pw.BorderSide(color: PdfColors.grey300, width: 0.6),
              horizontalInside: const pw.BorderSide(color: PdfColors.grey200, width: 0.5),
            ),
            defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
            columnWidths: const {
              0: pw.FlexColumnWidth(1.3),
              1: pw.FlexColumnWidth(1.8),
              2: pw.FlexColumnWidth(1.3),
              3: pw.FlexColumnWidth(2.2),
              4: pw.FlexColumnWidth(1.2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                children: colHeaders
                    .map((h) => pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 6),
                          child: pw.Text(h.toUpperCase(),
                              style: pw.TextStyle(fontSize: 8.5, fontWeight: pw.FontWeight.bold, letterSpacing: 0.3)),
                        ))
                    .toList(),
              ),
              if (rows.isEmpty)
                pw.TableRow(children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 6),
                    child: pw.Text('No transactions for this period.',
                        style: pw.TextStyle(fontSize: 9.5, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic)),
                  ),
                  ...List.generate(4, (_) => pw.Container()),
                ]),
              ...rows.map((row) => pw.TableRow(
                    children: List.generate(5, (i) => pw.Padding(
                          padding: const pw.EdgeInsets.symmetric(vertical: 7, horizontal: 6),
                          child: pw.Text(i < row.length ? row[i] : '', style: pw.TextStyle(fontSize: 9.5)),
                        )),
                  )),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300, width: 0.6),
              borderRadius: const pw.BorderRadius.vertical(bottom: pw.Radius.circular(5)),
            ),
            width: double.infinity,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.end,
              children: [
                pw.Text('Subtotal: ', style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold)),
                pw.Text(currency.format(subtotal),
                    style: pw.TextStyle(fontSize: 10.5, fontWeight: pw.FontWeight.bold, color: color)),
              ],
            ),
          ),
        ],
      );
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 28),
        header: (context) => _brandHeader(
          upriseLogo: upriseLogo, cictLogo: cictLogo, bsuLogo: bsuLogo, orgLogo: orgLogo,
        ),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          pw.Center(
            child: _titleBlock(
              eyebrow: 'FINANCIAL STATEMENT',
              title: 'Financial Report',
              subtitle: '$orgName  |  Period: $periodLabel',
              generatedAt: now,
            ),
          ),
          pw.SizedBox(height: 20),
          sectionTable('CASH INFLOW (Income)', PdfColors.green700, inflowRows, totalInflow),
          pw.SizedBox(height: 16),
          sectionTable('CASH OUTFLOW (Expenses)', PdfColors.red700, outflowRows, totalOutflow),
          pw.SizedBox(height: 18),
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: netFlow >= 0 ? PdfColors.green50 : PdfColors.red50,
              border: pw.Border.all(color: netFlow >= 0 ? PdfColors.green700 : PdfColors.red700, width: 1),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Total Cash Inflow', style: pw.TextStyle(fontSize: 11)),
                  pw.Text(currency.format(totalInflow), style: pw.TextStyle(fontSize: 11)),
                ],
              ),
              pw.SizedBox(height: 4),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Total Cash Outflow', style: pw.TextStyle(fontSize: 11)),
                  pw.Text('(${currency.format(totalOutflow)})', style: pw.TextStyle(fontSize: 11)),
                ],
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.symmetric(vertical: 8),
                child: pw.Divider(color: PdfColors.grey400, thickness: 0.8),
              ),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('NET CASH FLOW',
                      style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
                  pw.Text(currency.format(netFlow),
                      style: pw.TextStyle(
                          fontSize: 13,
                          fontWeight: pw.FontWeight.bold,
                          color: netFlow >= 0 ? PdfColors.green700 : PdfColors.red700)),
                ],
              ),
            ]),
          ),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 14),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300, width: 0.6),
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(children: [
              pw.Expanded(
                child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text('Prepared by', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                  pw.SizedBox(height: 14),
                  pw.Container(height: 0.75, color: PdfColors.grey400),
                  pw.SizedBox(height: 3),
                  pw.Text('Organization Treasurer / Officer', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                ]),
              ),
              pw.SizedBox(width: 30),
              pw.Expanded(
                child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text('Noted by', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                  pw.SizedBox(height: 14),
                  pw.Container(height: 0.75, color: PdfColors.grey400),
                  pw.SizedBox(height: 3),
                  pw.Text('Adviser / CICT Office', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
                ]),
              ),
            ]),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  // The BSU/CICT/Uprise logos never change at runtime, so re-decoding them
  // from the asset bundle on every single export call (as before) was pure
  // wasted CPU work that made repeated exports feel sluggish. Cache them
  // once per app session instead.
  static final Map<String, Future<pw.MemoryImage?>> _imageCache = {};

  static Future<pw.MemoryImage?> _loadImage(String path) {
    return _imageCache.putIfAbsent(path, () => _loadImageUncached(path));
  }

  static Future<pw.MemoryImage?> _loadImageUncached(String path) async {
    try {
      final byteData = await rootBundle.load(path);
      return pw.MemoryImage(byteData.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }
}
