import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class OrgExportPdf {
  static Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String subtitle = 'Bulacan State University - College of Information and Communications Technology (CICT)',
  }) async {
    final pdf = pw.Document();
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final now = DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) {
          return pw.Container(
            padding: const pw.EdgeInsets.only(bottom: 28),
            child: pw.Center(
              child: pw.Row(
                mainAxisSize: pw.MainAxisSize.min,
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  if (upriseLogo != null) pw.Image(upriseLogo, height: 36),
                  if (upriseLogo != null && cictLogo != null) pw.SizedBox(width: 18),
                  if (cictLogo != null) pw.Image(cictLogo, height: 40),
                  if ((upriseLogo != null || cictLogo != null) && bsuLogo != null) pw.SizedBox(width: 18),
                  if (bsuLogo != null) pw.Image(bsuLogo, height: 50),
                ],
              ),
            ),
          );
        },
        footer: (context) {
          return pw.Container(
            padding: const pw.EdgeInsets.only(top: 18),
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Divider(color: PdfColors.grey400, thickness: 0.5),
                pw.SizedBox(height: 8),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Generated by Uprise',
                      style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                    ),
                    pw.Text(
                      'Page ${context.pageNumber}',
                      style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                    ),
                  ],
                ),
              ],
            ),
          );
        },
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 18, horizontal: 20),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(10),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text(
                  title,
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  subtitle,
                  style: pw.TextStyle(fontSize: 12, fontStyle: pw.FontStyle.italic, color: PdfColors.grey700),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  'Uprise Student Directory System',
                  style: pw.TextStyle(fontSize: 11, color: PdfColors.grey800),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Generated: $now',
                  style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 18),
          pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.orange300, width: 1),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Table(
              defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
              columnWidths: {
                for (var i = 0; i < headers.length; i++) i: const pw.FlexColumnWidth(1),
              },
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.orange400),
                  children: headers.map((header) {
                    return pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 12, horizontal: 8),
                      child: pw.Text(
                        header,
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
                        textAlign: pw.TextAlign.center,
                      ),
                    );
                  }).toList(),
                ),
                ...rows.asMap().entries.map((entry) {
                  final row = entry.value;
                  final index = entry.key;
                  return pw.TableRow(
                    decoration: index.isEven ? const pw.BoxDecoration(color: PdfColors.orange100) : null,
                    children: List.generate(headers.length, (cellIndex) {
                      final value = cellIndex < row.length ? row[cellIndex] : '';
                      return pw.Padding(
                        padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 8),
                        child: pw.Text(value, style: pw.TextStyle(fontSize: 10, color: PdfColors.grey900)),
                      );
                    }),
                  );
                }),
              ],
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static Future<pw.MemoryImage?> _loadImage(String path) async {
    try {
      final byteData = await rootBundle.load(path);
      return pw.MemoryImage(byteData.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }
}
