import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class AdminExportPdf {
  static const PdfColor _accent = PdfColor.fromInt(0xFFB45309);

  /// Letterhead: UPRISE + CICT + BSU logos above a brand accent rule and a
  /// small-caps institution line. Admin exports span multiple orgs, so no
  /// single org logo is shown here (see OrgExportPdf for the org-scoped
  /// equivalent that does include one).
  static pw.Widget _brandHeader({
    required pw.MemoryImage? upriseLogo,
    required pw.MemoryImage? cictLogo,
    required pw.MemoryImage? bsuLogo,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 22),
      child: pw.Column(
        children: [
          pw.Row(
            mainAxisSize: pw.MainAxisSize.min,
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              if (upriseLogo != null) pw.Image(upriseLogo, height: 34),
              if (upriseLogo != null && cictLogo != null) pw.SizedBox(width: 16),
              if (cictLogo != null) pw.Image(cictLogo, height: 38),
              if ((upriseLogo != null || cictLogo != null) && bsuLogo != null) pw.SizedBox(width: 16),
              if (bsuLogo != null) pw.Image(bsuLogo, height: 46),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Container(height: 2, width: double.infinity, color: _accent),
          pw.SizedBox(height: 6),
          pw.Text(
            'BULACAN STATE UNIVERSITY  •  COLLEGE OF INFORMATION AND COMMUNICATIONS TECHNOLOGY',
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 7, color: PdfColors.grey600, letterSpacing: 0.6),
          ),
        ],
      ),
    );
  }

  static pw.Widget _brandFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 14),
      child: pw.Column(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Container(height: 0.75, width: double.infinity, color: PdfColors.grey300),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Uprise — CICT Administration System',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 8.5, color: PdfColors.grey600, fontWeight: pw.FontWeight.bold),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Letterhead-style title block: small-caps eyebrow label, bold title,
  /// optional subtitle, a short accent underline, then the generated-at
  /// timestamp.
  static pw.Widget _titleBlock({
    required String eyebrow,
    required String title,
    String? subtitle,
    required String generatedAt,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          eyebrow,
          style: pw.TextStyle(
              fontSize: 9, color: _accent, fontWeight: pw.FontWeight.bold, letterSpacing: 2.2),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          title,
          textAlign: pw.TextAlign.center,
          style: pw.TextStyle(fontSize: 23, fontWeight: pw.FontWeight.bold, color: PdfColors.grey900),
        ),
        if (subtitle != null && subtitle.isNotEmpty) ...[
          pw.SizedBox(height: 5),
          pw.Text(
            subtitle,
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
        pw.SizedBox(height: 10),
        pw.Container(width: 64, height: 2.2, color: _accent),
        pw.SizedBox(height: 10),
        pw.Text('Generated $generatedAt', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),
      ],
    );
  }

  static Future<Uint8List> generateTablePdf({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String subtitle = 'Official administrative records export',
  }) async {
    final pdf = pw.Document();
    final bsuLogo = await _loadImage('assets/images/bsu_logo.png');
    final cictLogo = await _loadImage('assets/images/cict_logo.png');
    final upriseLogo = await _loadImage('assets/images/logo.png');
    final now = DateFormat('MMMM d, yyyy  •  h:mm a').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 28, 32, 28),
        header: (context) => _brandHeader(upriseLogo: upriseLogo, cictLogo: cictLogo, bsuLogo: bsuLogo),
        footer: (context) => _brandFooter(context),
        build: (context) => [
          _titleBlock(
            eyebrow: 'EXPORTED RECORD',
            title: title,
            subtitle: subtitle,
            generatedAt: now,
          ),
          pw.SizedBox(height: 8),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
            margin: const pw.EdgeInsets.only(bottom: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Text(
              '${rows.length} record${rows.length == 1 ? '' : 's'}',
              style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Table(
            border: const pw.TableBorder(
              horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
            ),
            defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
            columnWidths: {
              for (var i = 0; i < headers.length; i++) i: const pw.FlexColumnWidth(1),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                  color: _accent,
                  borderRadius: pw.BorderRadius.vertical(top: pw.Radius.circular(4)),
                ),
                children: headers.map((header) {
                  return pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 8),
                    child: pw.Text(
                      header.toUpperCase(),
                      style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold, fontSize: 9, color: PdfColors.white, letterSpacing: 0.4),
                      textAlign: pw.TextAlign.center,
                    ),
                  );
                }).toList(),
              ),
              ...rows.asMap().entries.map((entry) {
                final row = entry.value;
                final index = entry.key;
                return pw.TableRow(
                  decoration: index.isEven ? const pw.BoxDecoration(color: PdfColors.orange50) : null,
                  children: List.generate(headers.length, (cellIndex) {
                    final value = cellIndex < row.length ? row[cellIndex] : '';
                    return pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(vertical: 9, horizontal: 8),
                      child: pw.Text(value, style: pw.TextStyle(fontSize: 9.5, color: PdfColors.grey900)),
                    );
                  }),
                );
              }),
            ],
          ),
          if (rows.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 20),
              child: pw.Center(
                child: pw.Text('No records to display.',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500, fontStyle: pw.FontStyle.italic)),
              ),
            ),
        ],
      ),
    );

    return pdf.save();
  }

  static Future<pw.MemoryImage?> _loadImage(String path) async {
    try {
      final byteData = await rootBundle.load(path);
      return pw.MemoryImage(byteData.buffer.asUint8List());
    } catch (_) {
      return null;
    }
  }
}
